Implemented PrizeDistributionFactory to move prize dist calc on-chain
pooltogether/v4-periphery pull request #9
Opened 2021-11-27 00:37 UTC by asselstine

2021-11-30 11:27 UTC, kamescg commented
@asselstine Does this need a review or ready to merge?

I think by tomorrow this might be blocking, because `v4-testnet` scripts will need this ABI published to NPM before moving forward with the updated deploy script that will use this new contract and the Timelock contract I am working on today.

2021-11-30 13:17 UTC, kamescg commented
Tracking temporary reference to `interface IPrizeDistributionFactory` in https://github.com/pooltogether/v4-timelocks/blob/pool-1910-v4-timelocks-develop-new-timelock-smart/contracts/DrawAndPrizeDistributionTimelock.sol#L8

When PR is merged update `v4-timelocks`

2021-11-30 17:51 UTC, asselstine commented
Yes!  Reviews would be great

2021-11-30 21:14 UTC, PierrickGT requested changes
Some minor changes and questions.
Also, we should remove the unused `newestDrawId` from the `PrizeTierHistory` contract.
https://github.com/pooltogether/v4-periphery/pull/9/files#diff-778c8645ac94af419acc3ce293c48834a903eb2376cf11e877a7db8591c6f5a9R56

2021-11-30 21:42 UTC, PierrickGT requested changes

2021-11-30 21:42 UTC, PierrickGT commented on test/PrizeDistributionFactory.test.ts
> +    describe('pushPrizeDistribution()', () => {
Test that this function is only callable by the owner or manager.

2021-11-30 21:42 UTC, PierrickGT commented on test/PrizeDistributionFactory.test.ts
> +    describe('setPrizeDistribution()', () => {
Test that this function is only callable by the owner and not the manager.

2021-12-01 00:08 UTC, asselstine commented on contracts/PrizeDistributionFactory.sol
> +        ticket = _ticket;
I think it's superfluous for a standard contract with a constructor

2021-12-01 00:08 UTC, asselstine commented on contracts/PrizeDistributionFactory.sol
> +        emit PushedPrizeDistribution(_drawId, _totalNetworkTicketSupply);
Yes, will rename if you like

If people are only listening to events then it's handy to have

2021-12-01 00:09 UTC, asselstine commented on contracts/PrizeDistributionFactory.sol
> +        emit SetPrizeDistribution(_drawId, _totalNetworkTicketSupply);
same same

2021-12-01 00:09 UTC, asselstine commented on contracts/PrizeDistributionFactory.sol
> +     * @param _drawId The draw from which to use the Draw and
:+1:

2021-12-02 08:10 UTC, merged